name: Lint the RDF vocabulary
on:
  pull_request:
    paths:
    - 'vocab/security/vocabulary.yml'
    - 'vocab/security/template.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/checkout/@v3
      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Lint Security Vocabulary
        run: |
          npm install yml2vocab
          npm update yml2vocab
          ./node_modules/.bin/yml2vocab -v vocab/vocabulary.yml -t vocab/template.html
